// @ts-check
import { describe, it, expect } from "vitest";

describe("comment_memory", () => {
  it("sanitizes valid memory IDs", async () => {
    const module = await import("./comment_memory.cjs");
    expect(module.sanitizeMemoryID("Session_1")).toBe("Session_1");
    expect(module.sanitizeMemoryID("notes-2026")).toBe("notes-2026");
  });

  it("rejects invalid memory IDs", async () => {
    const module = await import("./comment_memory.cjs");
    expect(module.sanitizeMemoryID("bad id")).toBeNull();
    expect(module.sanitizeMemoryID("../oops")).toBeNull();
  });

  it("builds managed comment body with xml memory marker", async () => {
    const module = await import("./comment_memory.cjs");
    const body = module.buildManagedMemoryBody("Hello world", "default", {
      includeFooter: false,
      runUrl: "https://example.com/run/1",
      workflowName: "Workflow",
      workflowSource: "",
      workflowSourceURL: "",
      historyUrl: undefined,
      triggeringIssueNumber: undefined,
      triggeringPRNumber: undefined,
    });
    expect(body).toContain("### Comment Memory");
    expect(body).toContain('<gh-aw-comment-memory id="default">');
    expect(body).toContain("Hello world");
    expect(body).toContain("</gh-aw-comment-memory>");
  });

  it("builds managed comment body with footer when enabled", async () => {
    const module = await import("./comment_memory.cjs");
    const body = module.buildManagedMemoryBody("Persist me", "session", {
      includeFooter: true,
      runUrl: "https://example.com/run/2",
      workflowName: "Workflow",
      workflowSource: "",
      workflowSourceURL: "",
      historyUrl: undefined,
      triggeringIssueNumber: 123,
      triggeringPRNumber: undefined,
    });
    expect(body).toContain("### Comment Memory");
    expect(body).toContain('<gh-aw-comment-memory id="session">');
    expect(body).toContain("Persist me");
    expect(body).toContain("> [!NOTE]");
    expect(body).toContain("> <summary>What this comment does</summary>");
    expect(body).toContain("Generated by");
    const memoryEndIdx = body.indexOf("</gh-aw-comment-memory>");
    const noteIdx = body.indexOf("> [!NOTE]");
    const footerIdx = body.indexOf("Generated by");
    expect(memoryEndIdx).toBeLessThan(noteIdx);
    expect(noteIdx).toBeLessThan(footerIdx);
  });

  it("throws E001 for invalid memory ID in managed body builder", async () => {
    const module = await import("./comment_memory.cjs");
    expect(() =>
      module.buildManagedMemoryBody("Persist me", "bad id", {
        includeFooter: false,
        runUrl: "https://example.com/run/3",
        workflowName: "Workflow",
        workflowSource: "",
        workflowSourceURL: "",
        historyUrl: undefined,
        triggeringIssueNumber: undefined,
        triggeringPRNumber: undefined,
      })
    ).toThrow("E001:");
  });

  it("finds only managed comments with provenance marker", async () => {
    const module = await import("./comment_memory.cjs");
    const github = {
      rest: {
        issues: {
          listComments: async () => ({
            data: [
              { id: 1, body: '<gh-aw-comment-memory id="default">\nold\n</gh-aw-comment-memory>' },
              {
                id: 2,
                body: '<gh-aw-comment-memory id="default">\nmanaged\n</gh-aw-comment-memory>\n\n<!-- gh-aw-agentic-workflow: Workflow, run: https://example.com -->',
              },
            ],
          }),
        },
      },
    };

    const found = await module.findManagedComment(github, "octo", "repo", 123, "default");
    expect(found?.id).toBe(2);
  });
});
